---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: present

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy backend"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm build
    pm2 start npm --name backend -- start
