---
- name: "extract backend files"
  become: yes
  unarchive:
    src: ~/project/backend.tgz
    dest: /home/ubuntu

- name: Recursively change ownership of backend
  file:
    path: /home/ubuntu/backend
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm i
    pm2 start npm --name backend -- start