---
- name: "extract backend files"
  become: yes
  unarchive:
    src: ~/project/backend.tgz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm i
    pm2 start npm --name backend -- start