- name: add node_exporter user
  become: yes
  user:
    name: node_exporter
    shell: /sbin/nologin
    append: yes
    state: present

- name: "download node_exporter"
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/ubuntu

- name: "extract node_exporter"
  unarchive:
    src: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: Copy node_exporter to /usr/local/bin
  become: yes
  copy:
    src: /home/ubuntu/node_exporter-1.0.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    directory_mode: yes
    mode: a+x

- name: Delete node_exporter directory
  file:
    path: /home/ubuntu/node_exporter-1.0.1.linux-amd64/
    state: absent

- name: Delete node_exporter tar
  file:
    path: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
    state: absent

- name: Copy node-exporter.service file
  become: yes
  template:
    src: ~/project/.circleci/ansible/roles/configure-prometheus-node-exporter/files/node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
    mode: a+x

- name: Start and enable service node-exporter, if not started
  become: yes
  service:
    name: node-exporter
    state: started
    enabled: yes